export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const LOGOUT = "LOGOUT"

export const REQ_APARTMENT_DATA = "REQ_APARTMENT_DATA"

export const GET_APARTMENT_DATA = "GET_APARTMENT_DATA"

export const REQ_APARTMENT_DATA_FAIL = "REQ_APARTMENT_DATA_FAIL"

export const GET_RESIDENT = "GET_RESIDENT"
